### ISSUE TITLE
clearEmptyId

### ISSUE THREAD

**Issue by zhoubo2015** [mescroll/mescroll-for-muiscroll#1]
mui主菜单里是多tab的列表；
每个list都配置了mescroll；
设置了clearEmptyId后，list下拉刷新显示不了，检查元素发现list的高度为0；
不设置clearEmptyId是没有问题的；

然后我不去设置这个clearEmptyId，我js里主动去清空list的内容（如list.innerHTML = "";）；发现列表顶部会卡住，不知道怎么解决了；

**Comment by mescroll** [comment]
结束下拉刷新的时候 先调用mescroll.endSuccess的方法  再调你初始化列表的方法;

因为mescroll.endSuccess内部会判断如果第一页,则会清空你配置clearEmptyId
所以要写在初始化列表方法的前面

**Comment by zhoubo2015** [comment]
嗯  的确是这样，谢谢
